language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - gcc-5
      - g++-5

before_install: pip install --user conan

script:
  - conan install --build
  - mkdir -p build && cd build
  - cmake .. && make
  - bin/conan-travis
